Promotion System/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :promotions, only: %i[index show new create] do
    post 'generate_coupons', on: :member
  end

  resources :product_categories, only: %i[index show new create]
  resources :coupons, only: %i[index show] do
    post 'inactivate', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :coupons, param: :code, only: %i[show] do
        post 'burn', on: :member
      end
      # get 'coupons/:code', to: 'coupons#show'
      # post 'coupons/:code/burn', to: 'coupons#burn'
    end
  end
end

Promotion System/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Promotion System/app/models/coupon.rb
# frozen_string_literal: true

class Coupon < ApplicationRecord
  belongs_to :promotion
  # delegate :discount_rate, to: :promotion

  enum status: { active: 0, inactive: 20, burn: 10 }
  validates :order, presence: true, on: :coupon_burn

  def title
    "#{code} (#{Coupon.human_attribute_name("status.#{status}")})"
  end

  def as_json(options = {})
    super({ methods: %i[discount_rate expiration_date],
            only: %i[] }.merge(options))
  end

  def burn!(order)
    self.order = order
    self.status = :burn
    save!(context: :coupon_burn)
  end

  def self.search(search)
    if search
      promotion_type = Promotion.find_by(code: search)
      if promotion_type
        where(promotion_id: promotion_type)
      else
        @coupons = Coupon.all
      end
    else
      @coupons = Coupon.all
    end
  end

  private

  def discount_rate
    promotion.discount_rate
  end

  def expiration_date
    I18n.l(promotion.expiration_date)
  end
end

Promotion System/app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
  has_many :product_category_promotions
  has_many :promotions, through: :product_category_promotions
end

Promotion System/app/models/product_category_promotion.rb
# frozen_string_literal: true

class ProductCategoryPromotion < ApplicationRecord
  belongs_to :product_category
  belongs_to :promotion
end

Promotion System/app/models/promotion.rb
# frozen_string_literal: true

class Promotion < ApplicationRecord
  has_many :coupons, dependent: :destroy
  has_many :product_category_promotions
  has_many :product_categories, through: :product_category_promotions

  validates :name, :code, :discount_rate,
            :coupon_quantity, :expiration_date,
            presence: true
  validates :code, uniqueness: true

  def generate_coupons!
    raise 'Cupons já foram gerados' if coupons.any?

    coupons
      .create_with(created_at: Time.zone.now, updated_at: Time.zone.now)
      .insert_all!(generate_coupons_code)
  end

  private

  def generate_coupons_code
    (1..coupon_quantity).map do |number|
      { code: "#{code}-#{'%04d' % number}" }
    end
  end
end

Promotion System/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validate :email_locaweb

  # def email_locaweb
  #   return if record.email.include? '@locaweb.com.br'
  #     record.errors.add(:email, 'O e-mail precisa ser @locaweb.com.br')
  #   end
end

Promotion System/app/controllers/api/v1/api_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ApiController < ActionController::API
    end
  end
end

Promotion System/app/controllers/api/v1/coupons_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CouponsController < ApiController
      before_action :verify_order_code, only: %i[burn]

      def show
        @coupon = Coupon.find_by(code: params[:code])
        return  render json: 'Cupom não encontrado', status: :not_found if @coupon.nil?

        render json: @coupon, status: :ok
      end

      def burn
        @coupon = Coupon.find_by!(code: params[:code])
        @coupon.burn!(params[:order][:code])
        render json: 'Cupom utilizado com sucesso', status: :ok
      rescue ActiveRecord::RecordInvalid
        render json: '', status: :unprocessable_entity
      end

      private

      # def verify_coupon_availability
      #   return if @coupon.available?

      #   render json: '', status: :precondition_failed
      # end

      def verify_order_code
        return if params.dig(:order, :code)

        render json: '', status: :precondition_failed
      end
    end
  end
end

Promotion System/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :warning, :notice, :success
end

Promotion System/app/controllers/coupons_controller.rb
# frozen_string_literal: true

class CouponsController < ApplicationController
  def inactivate
    @coupon = Coupon.find(params[:id])
    @coupon.inactive!
    flash[:success] = t('.success')
    redirect_to @coupon.promotion
  end

  def index
    @coupons = Coupon.all
    redirect_to promotions_path, alert:'Registre uma promoção para gerar um cupom' if @coupons.nil?
  end

  def search
    @coupons = Coupon.search(params[:search])
  end

  def show
    @coupon = Coupon.find(params[:id])
    flash.now[:notice] = 'Esse cupom não existe' if @coupons.nil?
  end

  def new
    @coupon = Coupon.new
  end

  private

  def coupon_params
    params
      .require(:coupon)
      .permit(:code, :order)
  end
end

Promotion System/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

Promotion System/app/controllers/product_categories_controller.rb
# frozen_string_literal: true

class ProductCategoriesController < ApplicationController
  def index
    @product_categories = ProductCategory.all
    redirect_to new_product_category_path, alert: 'Esta categoria de produtos não existe' if @product_categories.empty?
  end

  def show
    @product_categories = ProductCategory.find(params[:id])
  end

  def new
    @product_categories = ProductCategory.new
  end

  def create
    @product_categories = ProductCategory.new(category_params)
    if @product_categories.save
      redirect_to @product_categories
    else
      render :new
    end
  end

  private

  def category_params
    params
      .require(:product_category)
      .permit(:name, :code)
  end
end

Promotion System/app/controllers/promotions_controller.rb
# frozen_string_literal: true

class PromotionsController < ApplicationController
  before_action :authenticate_user!, only: %i[index]
  before_action :set_promotion, only: %i[show generate_coupons]

  def index
    @promotions = Promotion.all
  end

  def show
    @coupons = @promotion.coupons
  end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotion_params)
    if @promotion.save
      redirect_to @promotion
    else
      render :new
    end
  end

  def generate_coupons
    @promotion.generate_coupons!
    flash[:success] = 'Cupons gerados com sucesso'
    redirect_to @promotion
  end

  private

  def promotion_params
    params
      .require(:promotion)
      .permit(:name, :description, :code,
              :discount_rate, :expiration_date, :coupon_quantity,
              product_category_ids: [])
  end

  def promotion_params
    params
      .require(:promotion)
      .permit(:name, :description, :code,
              :discount_rate, :expiration_date, :coupon_quantity,
              product_category_ids: [])
  end

  def set_promotion
    @promotion = Promotion.find(params[:id])
  end
end

Promotion System/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

Promotion System/app/views/coupons/_coupon.html.erb
<dl>
  <dt><%= Coupon.human_attribute_name(:code) %></dt>
  <dd><%= coupon.title %></dd>
</dl>

<% if coupon.active? %>
  <%= link_to t('.inactivate'), inactivate_coupon_path(coupon), method: :post %>
<% end %>

Promotion System/app/views/coupons/index.html.erb
<div class="container">
<h2><%= link_to 'Voltar', root_path, method: :get, class: "btn btn-info" %></h2>
<hr>
<% @coupons.each do |coupon| %>
    <h3><%= link_to coupon.code, coupon %></h3>
    <p><b>Número da Promoção:</b> <%= coupon.promotion_id %></p>
    <p><b>Data de criação:</b> <%= coupon.created_at %></p>
    <p><b>Número do pedido:</b> <%= coupon.order %></p>
<% end %>

<h3> <%= link_to 'Emita um novo cupom',  promotions_path, class: "btn btn-primary" %> </h3>
<hr>
</div>

Promotion System/app/views/coupons/new.html.erb
<div class="container">
<%= form_with model: @coupon do |f| %>
<%= f.label :code, 'Código: ' %>
<%= f.text_field :code %>
<%= f.submit 'Criar Cupom', class: "btn btn-success" %>
<% end %>
</div>

Promotion System/app/views/coupons/show.html.erb
<div class="container">
<% if @coupon.nil? %>
  <%= 'Esse cupom não está cadastrado.' %>
<% else %>
    <p><b>Número do Cupom:</b> <%= @coupon.code %></p><hr>
    <h5><%= link_to 'Ver todos os cupons', @coupon, class: "btn btn-default" %></h5>
<% end %>
</div>

Promotion System/app/views/home/index.html.erb
<div class="container">
<h3>Bem vindo ao sistema de gestão de promoções</h3>
<hr>
<%= form_tag coupons_path, method: :get, class: "form-inline" do %>
<div class="form-group">
<%= label_tag :search, 'Digite o número do Cupom:' %>
<%= text_field_tag :search, params[:search], class: "form-control" %>
</div>
<%= submit_tag 'Buscar Cupom', class: "btn btn-default" %>

<% end %>
</div>

Promotion System/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">Promotion System</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Promoções", promotions_path, method: :get %></li>
      <li><%= link_to "Categorias de Produto", product_categories_path, method: :get %></li>
      <li><%= link_to "Cupons", coupons_path, method: :get %></li>
      <li><%= link_to "Login", new_user_session_path, method: :get %></li>
      <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>

Promotion System/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PromotionSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  </head>

  <body>
    <nav>
     <%= render 'layouts/navbar' %>

    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= flash[:alert] %></p>
    <% if flash[:success] %>
      <p><%= flash[:success] %></p>
    <% end %>
    <%= yield %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </body>
</html>

Promotion System/app/views/product_categories/index.html.erb
<div class="container">
<%= link_to 'Voltar', root_path, class: "btn btn-info" %>
<hr>
<h3><u> Todas as categorias de produtos: </u></h3>

<% @product_categories.each do |product_category| %>
 <h3><%= product_category.name %></h3>
 <p><strong><%= product_category.code %></strong></p>
<% end %>
<hr>
<%= link_to 'Registrar uma categoria para o produto', new_product_category_path, class: "btn btn-primary" %>
</div>

Promotion System/app/views/product_categories/new.html.erb
<div class="container">
<% if @product_categories.errors.any? %>
    <ul>
        <% @product_categories.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <%end%>
    </ul>
<%end%>

<%= form_with model: @product_categories do |f| %>
<%= f.label :name, 'Nome: ' %>
<%= f.text_field :name %>
<%= f.label :code, 'Código: ' %>
<%= f.text_field :code %>
<%= f.submit 'Criar categoria', class: "btn btn-success" %>
<% end %>
</div>

Promotion System/app/views/product_categories/show.html.erb
<div class="container">
<%= link_to 'Voltar', product_categories_path, class: "btn btn-info" %>
<hr>
<h4>Categoria:<b> <%= @product_categories.name %></h4>
<h4>Código:<b> <%= @product_categories.code %></h4>
</div>

Promotion System/app/views/promotions/index.html.erb
<div class="container">
<h2><%= link_to 'Voltar', root_path, method: :get, class: "btn btn-info" %></h2>
<hr>
<% @promotions.each do |promotion| %>
    <h3><%= link_to promotion.name, promotion %></h3>
    <p><%= promotion.description %></p>
    <p><%= number_to_percentage promotion.discount_rate, precision: 2, separator: ',' %></p>
<% end %>

<% if @promotions.empty? %>
<p> Nenhuma promoção cadastrada </p>
<% end %>

<h3> <%= link_to 'Registre uma nova promoção', new_promotion_path, class: "btn btn-primary" %> </h3>
<hr>
</div>

Promotion System/app/views/promotions/new.html.erb
<div class="container">
<% if @promotion.errors.any? %>
    <ul>
        <% @promotion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <%end%>
    </ul>
<%end%>

<div class="form-group">
<%= form_with class: "form-horizontal", model: @promotion do |f|  %>
<%= f.label :name, 'Nome' %>
<%= f.text_field :name, class: "form-control" %>
<%= f.label :description, 'Descrição' %>
<%= f.text_field :description, class: "form-control" %>
<%= f.label :code, 'Código' %>
<%= f.text_field :code, class: "form-control" %>
<%= f.label :discount_rate, 'Desconto' %>
<%= f.text_field :discount_rate, class: "form-control" %>
<%= f.label :coupon_quantity, 'Quantidade de cupons' %>
<%= f.number_field :coupon_quantity, min: 0, setp: 1, class: "form-control" %>
<%= f.label :expiration_date, 'Data de término' %>
<%= f.date_field :expiration_date, class: "form-control" %>
<br>
<div class="container">
<%= link_to 'Voltar', root_path, class: "btn btn-info" %>
<%= f.submit 'Criar promoção', class: "btn btn-default" %>
<% end %>
</div>
</div>

Promotion System/app/views/promotions/show.html.erb
<div class="container">
<h2><%= link_to 'Voltar', promotions_path, class: "btn btn-info" %></h2>
<hr>
<h1><%= @promotion.name %></h1>
<p><b>Descrição da Promoção:</b> <%= @promotion.description %></p>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Desconto </th>
      <th scope="col">Código</th>
      <th scope="col">Data de término</th>
      <th scope="col">Número de cupons</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">
      <%= number_to_percentage @promotion.discount_rate, separator: ',', precision: 2 %></th>
      <td><%= @promotion.code %></td>
      <td><%= @promotion.expiration_date.strftime('%d/%m/%Y') %></td>
      <td><%= @promotion.coupon_quantity %></td>
    </tr>
  </tbody>
</table>

<% if @promotion.coupons.empty? %>
  <%= link_to 'Emitir cupons', generate_coupons_promotion_path(@promotion), method: :post %>
<% else %>

    <h2>Cupons</h2>
  <%= render @promotion.coupons %>
<% end %>
</div>